# Generated by Django 4.2.19 on 2025-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
