# Generated by Django 4.2.19 on 2025-04-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
