;/*FB_PKG_DELIM*/

__d("PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8041911515933960"}),null);
__d("PolarisDesktopPostPageRelatedMediaGridQuery$Parameters",["PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisDesktopPostPageRelatedMediaGridQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisDesktopPostPageRelatedMediaGridQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisPostCommentsContainerQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8527751017247078"}),null);
__d("PolarisPostCommentsContainerQuery$Parameters",["PolarisIsLoggedIn.relayprovider","PolarisPostCommentsContainerQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisPostCommentsContainerQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisPostCommentsContainerQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisIsLoggedInrelayprovider:b("PolarisIsLoggedIn.relayprovider")}}};e.exports=a}),null);
__d("PolarisPostRootQuery$Parameters",["PolarisIsLoggedIn.relayprovider","PolarisPostRootQuery_instagramRelayOperation","PolarisShareSheetV3.relayprovider"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisPostRootQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisPostRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PolarisShareSheetV3relayprovider:b("PolarisShareSheetV3.relayprovider"),__relay_internal__pv__PolarisIsLoggedInrelayprovider:b("PolarisIsLoggedIn.relayprovider")}}};e.exports=a}),null);
__d("PolarisDesktopPostRoot.entrypoint",["JSResourceForInteraction","PolarisDesktopPostPageRelatedMediaGridQuery$Parameters","PolarisPostCommentsContainerQuery$Parameters","PolarisPostRootQuery$Parameters","gkx"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b=a.routeParams.shortcode;a=a.routeProps;var d=a.media_id;a=a.media_owner_id;return{queries:{polarisCommentsQuery:{options:{},parameters:c("PolarisPostCommentsContainerQuery$Parameters"),variables:{media_id:d}},polarisPostRootQuery:{options:{},parameters:c("PolarisPostRootQuery$Parameters"),variables:{shortcode:b}},polarisRelatedMediaQuery:{options:{},parameters:c("PolarisDesktopPostPageRelatedMediaGridQuery$Parameters"),variables:{count:c("gkx")("1878")?7:null,media_owner_id:a}}}}},root:c("JSResourceForInteraction")("PolarisDesktopPostRoot.react").__setRef("PolarisDesktopPostRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisSharerInfoQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9738280962848618"}),null);
__d("PolarisSharerInfoQuery$Parameters",["PolarisSharerInfoQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisSharerInfoQuery_instagramRelayOperation"),metadata:{is_distillery:!0},name:"PolarisSharerInfoQuery",operationKind:"query",text:null}};e.exports=a}),null);